Update find command in UG
AY2425S1-CS2103T-F13-1/tp pull request #312
Opened 2024-11-09 10:26 UTC by Clarenceeey

Fixes #306 

Update find command usage in user guide

2024-11-09 10:53 UTC, yhanyi approved these changes
LGTM

2024-11-09 14:31 UTC, notnotmax reviewed
Minor nits, then lgtm.

2024-11-09 14:31 UTC, notnotmax commented on docs/UserGuide.md
>    e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
A bit misleading, since in the line above it we say `jam ho` will not match `James Ho`. Maybe change this line to say `Hans;Bo` instead of `Hans Bo`?

2024-11-10 01:29 UTC, S-K-Y-Light requested changes

2024-11-10 01:29 UTC, S-K-Y-Light commented on docs/UserGuide.md
>    e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
Agreed. This Line is misleading. It definitely needs to be changed.

2024-11-10 08:48 UTC, notnotmax commented on docs/UserGuide.md
>    e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
Additionally, to address #250, maybe you could say that if no keyword is given, the command will show all students?

2024-11-11 01:01 UTC, S-K-Y-Light approved these changes
Seems Better. The Find Command is very descriptive and covers all/most issues during the PE-D. LGTM

2024-11-11 01:01 UTC, merged